---
title: "simsDR"
output: html_document
date: '2023-07-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


 


```{r}
 
results <- out
results[, coverage := CI_left <= ATE & CI_right >= ATE]
results[, sd := abs(CI_left -CI_right)/1.96/2]

results
results <- unique(results[, .(sd = mean(sd), se = sd(estimate-ATE), bias = abs(mean(estimate - ATE)), coverage = mean(coverage)), by = c( "misp",   "estimator", "lrnr")])
results[, rmse := sqrt(bias^2 + se^2)]
 
results
```



```{r}
results[results$lrnr=="xgboost",]

```
```{r}
library(data.table)

n_list <- c(  500, 1000, 2000, 3000, 4000, 5000  )
pos_list <- c(2 )

results <-
  rbindlist(unlist(lapply(n_list, function(n){
    unlist(lapply(pos_list, function(pos) {
  lapply(c(0), function(misp) {
    try({
      
    key <- paste0("DR_iter=", "1000", "_n=", n, "_pos=", pos )
   data <- fread(paste0("../simResultsDR/sim_results_", key, ".csv"))
   
   return(data)
    })
    return(data.table())
  })
}), recursive = F)
}), recursive = F))

 
results[, coverage := CI_left <= ATE & CI_right >= ATE]
results[, sd := abs(CI_left -CI_right)/1.96/2]
 
 results <- unique(results[, .(sd = mean(sd), se = sd(estimate-ATE), bias = abs(mean(estimate - ATE)), coverage = mean(coverage)), by = c("pos_const", "n", "misp",   "estimator", "lrnr")])
results[, rmse := sqrt(bias^2 + se^2)]
 
library(ggplot2)
w <- 7
h <- 5
results$misp <- c("Both", "Treatment", "Outcome", "Neither")[match(results$misp, c("1", "2", "3", "4"))]

for(pos_const in unique(results$pos_const)) {
for(lrnr in c("pooled")) {
  for(misp in c("Both", "Treatment", "Outcome", "Neither")) {
  tmp <- as.data.frame(results)[results$pos_const == pos_const,]
     #tmp <- as.data.frame(tmp)[tmp$lrnr == lrnr,]
     tmp <- as.data.frame(tmp)[tmp$misp == misp,]
 
  
  #maxval <- 3*min(tmp$rmse[tmp$n ==500])
     maxval <- max(tmp$rmse )
  tmp$bias <- pmin(tmp$bias, maxval)
  tmp$se <- pmin(tmp$se, maxval)
  tmp$mse <- pmin(tmp$rmse, maxval)
 
    limits <- c(0, maxval + .01)
 p <-  ggplot(tmp, aes(x= n, y = bias, color = lrnr, shape= lrnr)) + geom_point(size = 4) + geom_line( color="grey", linetype = "dashed") +  facet_wrap(~estimator, ncol =2)  + theme_bw() +     theme(  text = element_text(size=18), axis.text.x = element_text(size = 14 , hjust = 1, vjust = 0.5), legend.position = "bottom",   legend.box = "horizontal" 
  )  + labs(x = "Sample Size (n)", y = "Bias", color = "Estimator", group = "Estimator", shape= "Estimator") +  scale_y_continuous( limits = limits) 
  
  ggsave(   filename = paste0("DR=", pos_const,lrnr,misp, "Bias.pdf") , width = w, height = h)
 
      
 
      
                                      
                                     
  ggplot(tmp, aes(x= n, y = se, color = lrnr, shape= lrnr)) + geom_point(size = 4) + geom_line( color="grey", linetype = "dashed")  + facet_wrap(~estimator, ncol =2) + theme_bw()  +     theme(  text = element_text(size=18), axis.text.x = element_text(size = 14 , hjust = 1, vjust = 0.5), legend.position = "bottom",   legend.box = "horizontal" 
  )  + labs(x = "Sample Size (n)", y = "Standard Error", color = "Estimator", group = "Estimator", shape= "Estimator") +  scale_y_continuous( limits = limits)
  
  ggsave(filename = paste0("DR=", pos_const,lrnr,misp, "SE.pdf"), width = w, height = h)
  
  
  ggplot(tmp, aes(x= n, y = mse, color = lrnr, shape= lrnr)) + geom_point(size = 4)  + geom_line( color="grey", linetype = "dashed") + facet_wrap(~estimator, ncol =2) + theme_bw()  +     theme(  text = element_text(size=18), axis.text.x = element_text(size = 14 , hjust = 1, vjust = 0.5), legend.position = "bottom",   legend.box = "horizontal" 
  )  + labs(x = "Sample Size (n)", y = "Root Mean Square Error", color = "Estimator", group = "Estimator", shape= "Estimator")  +  scale_y_continuous( limits = limits)
  
  ggsave(filename = paste0("DR=", pos_const,lrnr,misp, "MSE.pdf"), width = w, height = h)
  
  p <- ggplot(tmp, aes(x= n, y = coverage, color = lrnr, shape= lrnr)) + geom_point(size = 4) + geom_line( color="grey", linetype = "dashed")  + facet_wrap(~estimator, ncol =2)+ scale_y_continuous(limits = c(min(tmp$coverage), 0.97)) + geom_hline(yintercept = 0.95, color = "grey") + theme_bw() +     theme(  text = element_text(size=18), axis.text.x = element_text(size = 14 , hjust = 1, vjust = 0.5), legend.position = "bottom",   legend.box = "horizontal" 
  )  + labs(x = "Sample Size (n)", y = "CI Coverage", color = "Estimator", group = "Estimator", shape= "Estimator")  
  
  
  ggsave(filename = paste0("DR=", pos_const,lrnr,misp, "CI.pdf"), width = w, height = h)
  }
}}


  p <- ggplot(tmp, aes(x= n, y = coverage, color = lrnr, shape= lrnr)) + geom_point(size = 4) + facet_wrap(~estimator, ncol =2)+ scale_y_log10() + geom_hline(yintercept = 0.95, color = "grey") + theme_bw() +     theme(  text = element_text(size=18), axis.text.x = element_text(size = 14 , hjust = 1, vjust = 0.5), legend.position = "bottom",   legend.box = "horizontal" , legend.title = element_blank()
  )  + labs(x = "Sample Size (n)", y = "CI Coverage", color = "estimator", group = "estimator", shape= "estimator")  
 

```



```{r}

results[n >= 1000 & pos == 4e-02]

```
