---
title: "help"
output: html_document
date: '2023-04-10'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
library(SuperLearner)
library(tmle)
 
n <- 1000
# Baseline variable
W <- runif(n =  1000, min = -1, max = 1)
# continuous treatment/biomarker/immune response
A <- rnorm(n, mean = W, sd = 1)

# Discrete time to event variable
T_inf <- ceiling(rexp(n, rate = 0.1))
# Discrete time to censoring/loss-of-follow-up variable
C <-  ceiling(rexp(n, rate = 0.05))
# Censoring indicator: takes value 1 if infection is observed and 0 otherwise.
Delta <- as.numeric(C > T_inf)
# Binary outcome defined as indicator of being infected before a given reference time
t_ref <- median(T_inf)
Y <- as.numeric(T_inf <= t_ref)
#  Thresholded biomarker:
thresholds <-quantile(A, c(0.1, 0.5))
for(thresh in thresholds) {
  A_thresh <- as.numeric(A >= threshold)
  sl_library <- c("SL.glmnet", "tmle.SL.dbarts", "SL.earth", "SL.gam", "SL.ranger" )
  sl_library <- "SL.gam" # for this example/speed, I'll just use GAM.
  tmle(Y, A, W, Delta = Delta, Q.SL.library = sl_library, )
  
}
  
# Use the SuperLearner package to specify a machine-learning ensemble for the outcome regression and propensity score
 

 
```
