---
title: "sims"
output: html_document
date: '2023-04-03'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# both plugin R learner and plugin T-learner


#devtools::install_github("tlverse/hal9001", ref = "screeningHAL")1

n <- 5000
d <- 7
W <- replicate(d, runif(n, -1, 1)) 
colnames(W) <- paste0("W", 1:d)
c<- c(1, 2, 3)
c <- 0
pi_hard <- plogis(c * ((1+ 1.5*W[,1])*sin(5*W[,1]) + (1 + 1.5*W[,2])* cos(5*W[,2]) + sin(3*W[,3]) + sin(5*W[,7]) + cos(3*W[,6])))
range(pi_hard)
hist(pi_hard)
A <- rbinom(n, 1, pi_hard)
mu0 <-  W[,1] + sin(5*W[,2]) + W[,3] + (1 + W[,4])*sin(5*W[,4]) + cos(5*W[,5])
mu0 <-  W[,1] + W[,2]  + W[,4] + W[,5]
tau <- 1 + W[,1] + W[,3] + W[,5]
Y <- rnorm(n,  mu0 + A * tau, 0.5)

 
get_estimates <- function(W, A, Y,iter) {

fit_T <- fit_hal_cate(W, A, Y,  max_degree = 1, num_knots = c(100), smoothness_orders = 1,max_degree_cate =1, num_knots_cate = 100, smoothness_orders_cate = 1,    screen_variables = TRUE) 
ate_T <- unlist(inference_cate(fit_T)) 
ate_T[1] <- "Tlearner"


lrnr_A <- Lrnr_gam$new(family = "binomial")
fit_R <- fit_hal_pcate(W, A, Y, lrnr_Y = NULL, lrnr_A = lrnr_A,  max_degree =2, num_knots = 50,  max_degree_cate = 1, num_knots_cate = 10, smoothness_orders_cate = 1,    screen_variables = TRUE, formula_cate = ~ h(.))
ate_R<-  unlist(inference_cate(fit_R))
ate_R[1] <- "Rlearner"

lrnr_A <- fit_R$internal$fit_EAW
fit_R_intercept <- fit_hal_pcate(W, A, Y, lrnr_Y = NULL, lrnr_A = lrnr_A,  max_degree =2, num_knots = 50,  max_degree_cate = 1, num_knots_cate = 2, smoothness_orders_cate = 1,    screen_variables = TRUE, formula_cate = ~ h(W7))
mean(fit_R$internal$data$tau_relaxed)
ate_intercept <-  unlist(inference_cate(fit_R_intercept))
ate_intercept[1] <- "intercept"

pi <- fit_R$internal$data$pi
mu1 <- fit_T$internal$data$mu1
mu0 <- fit_T$internal$data$mu1
mu <- ifelse(A==1, mu1, mu0)
IF <- mu1 - mu0 + (A - pi) / ((1-pi)*pi) * (Y - mu)
est_AIPW <-  mean(IF)
CI <- est_AIPW + 1.96*c(-1,1)*sd(IF)/sqrt(n)
ate_aipw <- c("AIPW", est_AIPW, sd(IF)/sqrt(n), CI)
names(ate_aipw) <- c("method", "coef","se", "CI_left", "CI_right")

mat <- cbind(iter,rbind(ate_T, ate_R, ate_intercept, ate_aipw))
colnames(mat)  <- c("iter", "method", "coef","se", "CI_left", "CI_right")
return(mat)
}

 

#AIPW
#  partially linear correct
# partially linear intercept
  

```
